services:
  nginx:
    ports:
      - "${LOCAL_HTTP_PORT:-80}:80"

networks:
  registry-net:
    internal: false
  dokploy-network:
    name: ${LOCAL_DOKPLOY_NETWORK:-cr-local-dokploy-network}
    external: false
    driver: bridge
    internal: false
